### ISSUE TITLE
直播视频第一次加载没有显示画面，旋转画面之后才显示

### ISSUE THREAD

**Issue by BlessNeo** [Hikvision-Ezviz/EZUIKit-iOS#6]
Demo 也是同样的问题。
iOS11上会有这样的问题。
还有，怎么设置直播画面的填充方式呢？

**Comment by Ezviz-LinYong** [comment]
1.3版本已修复iOS 11系统的显示问题，内部没有实现修改填充方式的功能

**Comment by BlessNeo** [comment]
@Ezviz-LinYong 昨天就看到官网更新了，666
